/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EntrepriseRouteImport } from './routes/entreprise'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ApprendreRouteImport } from './routes/apprendre'
import { Route as ActivationRouteImport } from './routes/activation'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseRoute = EntrepriseRouteImport.update({
  id: '/entreprise',
  path: '/entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprendreRoute = ApprendreRouteImport.update({
  id: '/apprendre',
  path: '/apprendre',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationRoute = ActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/apprendre': typeof ApprendreRoute
  '/consent': typeof ConsentRoute
  '/entreprise': typeof EntrepriseRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/produits': typeof ProduitsRoute
  '/report': typeof ReportRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/apprendre': typeof ApprendreRoute
  '/consent': typeof ConsentRoute
  '/entreprise': typeof EntrepriseRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/produits': typeof ProduitsRoute
  '/report': typeof ReportRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/apprendre': typeof ApprendreRoute
  '/consent': typeof ConsentRoute
  '/entreprise': typeof EntrepriseRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/produits': typeof ProduitsRoute
  '/report': typeof ReportRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activation'
    | '/apprendre'
    | '/consent'
    | '/entreprise'
    | '/faq'
    | '/login'
    | '/produits'
    | '/report'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activation'
    | '/apprendre'
    | '/consent'
    | '/entreprise'
    | '/faq'
    | '/login'
    | '/produits'
    | '/report'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/activation'
    | '/apprendre'
    | '/consent'
    | '/entreprise'
    | '/faq'
    | '/login'
    | '/produits'
    | '/report'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivationRoute: typeof ActivationRoute
  ApprendreRoute: typeof ApprendreRoute
  ConsentRoute: typeof ConsentRoute
  EntrepriseRoute: typeof EntrepriseRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  ProduitsRoute: typeof ProduitsRoute
  ReportRoute: typeof ReportRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise': {
      id: '/entreprise'
      path: '/entreprise'
      fullPath: '/entreprise'
      preLoaderRoute: typeof EntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apprendre': {
      id: '/apprendre'
      path: '/apprendre'
      fullPath: '/apprendre'
      preLoaderRoute: typeof ApprendreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation': {
      id: '/activation'
      path: '/activation'
      fullPath: '/activation'
      preLoaderRoute: typeof ActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivationRoute: ActivationRoute,
  ApprendreRoute: ApprendreRoute,
  ConsentRoute: ConsentRoute,
  EntrepriseRoute: EntrepriseRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  ProduitsRoute: ProduitsRoute,
  ReportRoute: ReportRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
