/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelAgentsRouteImport } from './routes/travel-agents'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SenseiPayRouteImport } from './routes/sensei-pay'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProtectRouteImport } from './routes/protect'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as CustomiseRouteImport } from './routes/customise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AirlinesSlugRouteImport } from './routes/airlines.$slug'

const TravelAgentsRoute = TravelAgentsRouteImport.update({
  id: '/travel-agents',
  path: '/travel-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SenseiPayRoute = SenseiPayRouteImport.update({
  id: '/sensei-pay',
  path: '/sensei-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectRoute = ProtectRouteImport.update({
  id: '/protect',
  path: '/protect',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomiseRoute = CustomiseRouteImport.update({
  id: '/customise',
  path: '/customise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AirlinesSlugRoute = AirlinesSlugRouteImport.update({
  id: '/airlines/$slug',
  path: '/airlines/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customise': typeof CustomiseRoute
  '/details': typeof DetailsRoute
  '/manage': typeof ManageRoute
  '/protect': typeof ProtectRoute
  '/results': typeof ResultsRoute
  '/sensei-pay': typeof SenseiPayRoute
  '/summary': typeof SummaryRoute
  '/travel-agents': typeof TravelAgentsRoute
  '/airlines/$slug': typeof AirlinesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customise': typeof CustomiseRoute
  '/details': typeof DetailsRoute
  '/manage': typeof ManageRoute
  '/protect': typeof ProtectRoute
  '/results': typeof ResultsRoute
  '/sensei-pay': typeof SenseiPayRoute
  '/summary': typeof SummaryRoute
  '/travel-agents': typeof TravelAgentsRoute
  '/airlines/$slug': typeof AirlinesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customise': typeof CustomiseRoute
  '/details': typeof DetailsRoute
  '/manage': typeof ManageRoute
  '/protect': typeof ProtectRoute
  '/results': typeof ResultsRoute
  '/sensei-pay': typeof SenseiPayRoute
  '/summary': typeof SummaryRoute
  '/travel-agents': typeof TravelAgentsRoute
  '/airlines/$slug': typeof AirlinesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customise'
    | '/details'
    | '/manage'
    | '/protect'
    | '/results'
    | '/sensei-pay'
    | '/summary'
    | '/travel-agents'
    | '/airlines/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customise'
    | '/details'
    | '/manage'
    | '/protect'
    | '/results'
    | '/sensei-pay'
    | '/summary'
    | '/travel-agents'
    | '/airlines/$slug'
  id:
    | '__root__'
    | '/'
    | '/customise'
    | '/details'
    | '/manage'
    | '/protect'
    | '/results'
    | '/sensei-pay'
    | '/summary'
    | '/travel-agents'
    | '/airlines/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomiseRoute: typeof CustomiseRoute
  DetailsRoute: typeof DetailsRoute
  ManageRoute: typeof ManageRoute
  ProtectRoute: typeof ProtectRoute
  ResultsRoute: typeof ResultsRoute
  SenseiPayRoute: typeof SenseiPayRoute
  SummaryRoute: typeof SummaryRoute
  TravelAgentsRoute: typeof TravelAgentsRoute
  AirlinesSlugRoute: typeof AirlinesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel-agents': {
      id: '/travel-agents'
      path: '/travel-agents'
      fullPath: '/travel-agents'
      preLoaderRoute: typeof TravelAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensei-pay': {
      id: '/sensei-pay'
      path: '/sensei-pay'
      fullPath: '/sensei-pay'
      preLoaderRoute: typeof SenseiPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protect': {
      id: '/protect'
      path: '/protect'
      fullPath: '/protect'
      preLoaderRoute: typeof ProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customise': {
      id: '/customise'
      path: '/customise'
      fullPath: '/customise'
      preLoaderRoute: typeof CustomiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airlines/$slug': {
      id: '/airlines/$slug'
      path: '/airlines/$slug'
      fullPath: '/airlines/$slug'
      preLoaderRoute: typeof AirlinesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomiseRoute: CustomiseRoute,
  DetailsRoute: DetailsRoute,
  ManageRoute: ManageRoute,
  ProtectRoute: ProtectRoute,
  ResultsRoute: ResultsRoute,
  SenseiPayRoute: SenseiPayRoute,
  SummaryRoute: SummaryRoute,
  TravelAgentsRoute: TravelAgentsRoute,
  AirlinesSlugRoute: AirlinesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
