/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoutienMarchandsRouteImport } from './routes/soutien-marchands'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PresseRouteImport } from './routes/presse'
import { Route as OuPayerRouteImport } from './routes/ou-payer'
import { Route as MoyensPaiementRouteImport } from './routes/moyens-paiement'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestisseursRouteImport } from './routes/investisseurs'
import { Route as EntrepriseRouteImport } from './routes/entreprise'
import { Route as EligibiliteRouteImport } from './routes/eligibilite'
import { Route as DeveloppeursRouteImport } from './routes/developpeurs'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrieresRouteImport } from './routes/carrieres'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaiementsIndexRouteImport } from './routes/paiements.index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as PaiementsPlanIdRouteImport } from './routes/paiements.$planId'
import { Route as MerchantWebhooksRouteImport } from './routes/merchant.webhooks'
import { Route as MerchantTransactionsRouteImport } from './routes/merchant.transactions'
import { Route as MerchantTerminalRouteImport } from './routes/merchant.terminal'
import { Route as MerchantPayoutsRouteImport } from './routes/merchant.payouts'
import { Route as MerchantApiKeysRouteImport } from './routes/merchant.api-keys'
import { Route as CheckoutMerciRouteImport } from './routes/checkout_.merci'
import { Route as AideSujetRouteImport } from './routes/aide.$sujet'
import { Route as AideSujetArticleRouteImport } from './routes/aide.$sujet.$article'

const SoutienMarchandsRoute = SoutienMarchandsRouteImport.update({
  id: '/soutien-marchands',
  path: '/soutien-marchands',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PresseRoute = PresseRouteImport.update({
  id: '/presse',
  path: '/presse',
  getParentRoute: () => rootRouteImport,
} as any)
const OuPayerRoute = OuPayerRouteImport.update({
  id: '/ou-payer',
  path: '/ou-payer',
  getParentRoute: () => rootRouteImport,
} as any)
const MoyensPaiementRoute = MoyensPaiementRouteImport.update({
  id: '/moyens-paiement',
  path: '/moyens-paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestisseursRoute = InvestisseursRouteImport.update({
  id: '/investisseurs',
  path: '/investisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseRoute = EntrepriseRouteImport.update({
  id: '/entreprise',
  path: '/entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibiliteRoute = EligibiliteRouteImport.update({
  id: '/eligibilite',
  path: '/eligibilite',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloppeursRoute = DeveloppeursRouteImport.update({
  id: '/developpeurs',
  path: '/developpeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrieresRoute = CarrieresRouteImport.update({
  id: '/carrieres',
  path: '/carrieres',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsIndexRoute = PaiementsIndexRouteImport.update({
  id: '/paiements/',
  path: '/paiements/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const PaiementsPlanIdRoute = PaiementsPlanIdRouteImport.update({
  id: '/paiements/$planId',
  path: '/paiements/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantWebhooksRoute = MerchantWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantTransactionsRoute = MerchantTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantTerminalRoute = MerchantTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantPayoutsRoute = MerchantPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantApiKeysRoute = MerchantApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => MerchantRoute,
} as any)
const CheckoutMerciRoute = CheckoutMerciRouteImport.update({
  id: '/checkout_/merci',
  path: '/checkout/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const AideSujetRoute = AideSujetRouteImport.update({
  id: '/$sujet',
  path: '/$sujet',
  getParentRoute: () => AideRoute,
} as any)
const AideSujetArticleRoute = AideSujetArticleRouteImport.update({
  id: '/$article',
  path: '/$article',
  getParentRoute: () => AideSujetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aide': typeof AideRouteWithChildren
  '/carrieres': typeof CarrieresRoute
  '/checkout': typeof CheckoutRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/developpeurs': typeof DeveloppeursRoute
  '/eligibilite': typeof EligibiliteRoute
  '/entreprise': typeof EntrepriseRoute
  '/investisseurs': typeof InvestisseursRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/moyens-paiement': typeof MoyensPaiementRoute
  '/ou-payer': typeof OuPayerRoute
  '/presse': typeof PresseRoute
  '/profil': typeof ProfilRoute
  '/score': typeof ScoreRoute
  '/signup': typeof SignupRoute
  '/soutien-marchands': typeof SoutienMarchandsRoute
  '/aide/$sujet': typeof AideSujetRouteWithChildren
  '/checkout/merci': typeof CheckoutMerciRoute
  '/merchant/api-keys': typeof MerchantApiKeysRoute
  '/merchant/payouts': typeof MerchantPayoutsRoute
  '/merchant/terminal': typeof MerchantTerminalRoute
  '/merchant/transactions': typeof MerchantTransactionsRoute
  '/merchant/webhooks': typeof MerchantWebhooksRoute
  '/paiements/$planId': typeof PaiementsPlanIdRoute
  '/merchant/': typeof MerchantIndexRoute
  '/paiements/': typeof PaiementsIndexRoute
  '/aide/$sujet/$article': typeof AideSujetArticleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aide': typeof AideRouteWithChildren
  '/carrieres': typeof CarrieresRoute
  '/checkout': typeof CheckoutRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/developpeurs': typeof DeveloppeursRoute
  '/eligibilite': typeof EligibiliteRoute
  '/entreprise': typeof EntrepriseRoute
  '/investisseurs': typeof InvestisseursRoute
  '/login': typeof LoginRoute
  '/moyens-paiement': typeof MoyensPaiementRoute
  '/ou-payer': typeof OuPayerRoute
  '/presse': typeof PresseRoute
  '/profil': typeof ProfilRoute
  '/score': typeof ScoreRoute
  '/signup': typeof SignupRoute
  '/soutien-marchands': typeof SoutienMarchandsRoute
  '/aide/$sujet': typeof AideSujetRouteWithChildren
  '/checkout/merci': typeof CheckoutMerciRoute
  '/merchant/api-keys': typeof MerchantApiKeysRoute
  '/merchant/payouts': typeof MerchantPayoutsRoute
  '/merchant/terminal': typeof MerchantTerminalRoute
  '/merchant/transactions': typeof MerchantTransactionsRoute
  '/merchant/webhooks': typeof MerchantWebhooksRoute
  '/paiements/$planId': typeof PaiementsPlanIdRoute
  '/merchant': typeof MerchantIndexRoute
  '/paiements': typeof PaiementsIndexRoute
  '/aide/$sujet/$article': typeof AideSujetArticleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aide': typeof AideRouteWithChildren
  '/carrieres': typeof CarrieresRoute
  '/checkout': typeof CheckoutRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/developpeurs': typeof DeveloppeursRoute
  '/eligibilite': typeof EligibiliteRoute
  '/entreprise': typeof EntrepriseRoute
  '/investisseurs': typeof InvestisseursRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/moyens-paiement': typeof MoyensPaiementRoute
  '/ou-payer': typeof OuPayerRoute
  '/presse': typeof PresseRoute
  '/profil': typeof ProfilRoute
  '/score': typeof ScoreRoute
  '/signup': typeof SignupRoute
  '/soutien-marchands': typeof SoutienMarchandsRoute
  '/aide/$sujet': typeof AideSujetRouteWithChildren
  '/checkout_/merci': typeof CheckoutMerciRoute
  '/merchant/api-keys': typeof MerchantApiKeysRoute
  '/merchant/payouts': typeof MerchantPayoutsRoute
  '/merchant/terminal': typeof MerchantTerminalRoute
  '/merchant/transactions': typeof MerchantTransactionsRoute
  '/merchant/webhooks': typeof MerchantWebhooksRoute
  '/paiements/$planId': typeof PaiementsPlanIdRoute
  '/merchant/': typeof MerchantIndexRoute
  '/paiements/': typeof PaiementsIndexRoute
  '/aide/$sujet/$article': typeof AideSujetArticleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/aide'
    | '/carrieres'
    | '/checkout'
    | '/comment-ca-marche'
    | '/developpeurs'
    | '/eligibilite'
    | '/entreprise'
    | '/investisseurs'
    | '/login'
    | '/merchant'
    | '/moyens-paiement'
    | '/ou-payer'
    | '/presse'
    | '/profil'
    | '/score'
    | '/signup'
    | '/soutien-marchands'
    | '/aide/$sujet'
    | '/checkout/merci'
    | '/merchant/api-keys'
    | '/merchant/payouts'
    | '/merchant/terminal'
    | '/merchant/transactions'
    | '/merchant/webhooks'
    | '/paiements/$planId'
    | '/merchant/'
    | '/paiements/'
    | '/aide/$sujet/$article'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/aide'
    | '/carrieres'
    | '/checkout'
    | '/comment-ca-marche'
    | '/developpeurs'
    | '/eligibilite'
    | '/entreprise'
    | '/investisseurs'
    | '/login'
    | '/moyens-paiement'
    | '/ou-payer'
    | '/presse'
    | '/profil'
    | '/score'
    | '/signup'
    | '/soutien-marchands'
    | '/aide/$sujet'
    | '/checkout/merci'
    | '/merchant/api-keys'
    | '/merchant/payouts'
    | '/merchant/terminal'
    | '/merchant/transactions'
    | '/merchant/webhooks'
    | '/paiements/$planId'
    | '/merchant'
    | '/paiements'
    | '/aide/$sujet/$article'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/aide'
    | '/carrieres'
    | '/checkout'
    | '/comment-ca-marche'
    | '/developpeurs'
    | '/eligibilite'
    | '/entreprise'
    | '/investisseurs'
    | '/login'
    | '/merchant'
    | '/moyens-paiement'
    | '/ou-payer'
    | '/presse'
    | '/profil'
    | '/score'
    | '/signup'
    | '/soutien-marchands'
    | '/aide/$sujet'
    | '/checkout_/merci'
    | '/merchant/api-keys'
    | '/merchant/payouts'
    | '/merchant/terminal'
    | '/merchant/transactions'
    | '/merchant/webhooks'
    | '/paiements/$planId'
    | '/merchant/'
    | '/paiements/'
    | '/aide/$sujet/$article'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AideRoute: typeof AideRouteWithChildren
  CarrieresRoute: typeof CarrieresRoute
  CheckoutRoute: typeof CheckoutRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  DeveloppeursRoute: typeof DeveloppeursRoute
  EligibiliteRoute: typeof EligibiliteRoute
  EntrepriseRoute: typeof EntrepriseRoute
  InvestisseursRoute: typeof InvestisseursRoute
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  MoyensPaiementRoute: typeof MoyensPaiementRoute
  OuPayerRoute: typeof OuPayerRoute
  PresseRoute: typeof PresseRoute
  ProfilRoute: typeof ProfilRoute
  ScoreRoute: typeof ScoreRoute
  SignupRoute: typeof SignupRoute
  SoutienMarchandsRoute: typeof SoutienMarchandsRoute
  CheckoutMerciRoute: typeof CheckoutMerciRoute
  PaiementsPlanIdRoute: typeof PaiementsPlanIdRoute
  PaiementsIndexRoute: typeof PaiementsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soutien-marchands': {
      id: '/soutien-marchands'
      path: '/soutien-marchands'
      fullPath: '/soutien-marchands'
      preLoaderRoute: typeof SoutienMarchandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presse': {
      id: '/presse'
      path: '/presse'
      fullPath: '/presse'
      preLoaderRoute: typeof PresseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ou-payer': {
      id: '/ou-payer'
      path: '/ou-payer'
      fullPath: '/ou-payer'
      preLoaderRoute: typeof OuPayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moyens-paiement': {
      id: '/moyens-paiement'
      path: '/moyens-paiement'
      fullPath: '/moyens-paiement'
      preLoaderRoute: typeof MoyensPaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investisseurs': {
      id: '/investisseurs'
      path: '/investisseurs'
      fullPath: '/investisseurs'
      preLoaderRoute: typeof InvestisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise': {
      id: '/entreprise'
      path: '/entreprise'
      fullPath: '/entreprise'
      preLoaderRoute: typeof EntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibilite': {
      id: '/eligibilite'
      path: '/eligibilite'
      fullPath: '/eligibilite'
      preLoaderRoute: typeof EligibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developpeurs': {
      id: '/developpeurs'
      path: '/developpeurs'
      fullPath: '/developpeurs'
      preLoaderRoute: typeof DeveloppeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrieres': {
      id: '/carrieres'
      path: '/carrieres'
      fullPath: '/carrieres'
      preLoaderRoute: typeof CarrieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements/': {
      id: '/paiements/'
      path: '/paiements'
      fullPath: '/paiements/'
      preLoaderRoute: typeof PaiementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/paiements/$planId': {
      id: '/paiements/$planId'
      path: '/paiements/$planId'
      fullPath: '/paiements/$planId'
      preLoaderRoute: typeof PaiementsPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/webhooks': {
      id: '/merchant/webhooks'
      path: '/webhooks'
      fullPath: '/merchant/webhooks'
      preLoaderRoute: typeof MerchantWebhooksRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/transactions': {
      id: '/merchant/transactions'
      path: '/transactions'
      fullPath: '/merchant/transactions'
      preLoaderRoute: typeof MerchantTransactionsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/terminal': {
      id: '/merchant/terminal'
      path: '/terminal'
      fullPath: '/merchant/terminal'
      preLoaderRoute: typeof MerchantTerminalRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/payouts': {
      id: '/merchant/payouts'
      path: '/payouts'
      fullPath: '/merchant/payouts'
      preLoaderRoute: typeof MerchantPayoutsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/api-keys': {
      id: '/merchant/api-keys'
      path: '/api-keys'
      fullPath: '/merchant/api-keys'
      preLoaderRoute: typeof MerchantApiKeysRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/checkout_/merci': {
      id: '/checkout_/merci'
      path: '/checkout/merci'
      fullPath: '/checkout/merci'
      preLoaderRoute: typeof CheckoutMerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/$sujet': {
      id: '/aide/$sujet'
      path: '/$sujet'
      fullPath: '/aide/$sujet'
      preLoaderRoute: typeof AideSujetRouteImport
      parentRoute: typeof AideRoute
    }
    '/aide/$sujet/$article': {
      id: '/aide/$sujet/$article'
      path: '/$article'
      fullPath: '/aide/$sujet/$article'
      preLoaderRoute: typeof AideSujetArticleRouteImport
      parentRoute: typeof AideSujetRoute
    }
  }
}

interface AideSujetRouteChildren {
  AideSujetArticleRoute: typeof AideSujetArticleRoute
}

const AideSujetRouteChildren: AideSujetRouteChildren = {
  AideSujetArticleRoute: AideSujetArticleRoute,
}

const AideSujetRouteWithChildren = AideSujetRoute._addFileChildren(
  AideSujetRouteChildren,
)

interface AideRouteChildren {
  AideSujetRoute: typeof AideSujetRouteWithChildren
}

const AideRouteChildren: AideRouteChildren = {
  AideSujetRoute: AideSujetRouteWithChildren,
}

const AideRouteWithChildren = AideRoute._addFileChildren(AideRouteChildren)

interface MerchantRouteChildren {
  MerchantApiKeysRoute: typeof MerchantApiKeysRoute
  MerchantPayoutsRoute: typeof MerchantPayoutsRoute
  MerchantTerminalRoute: typeof MerchantTerminalRoute
  MerchantTransactionsRoute: typeof MerchantTransactionsRoute
  MerchantWebhooksRoute: typeof MerchantWebhooksRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantApiKeysRoute: MerchantApiKeysRoute,
  MerchantPayoutsRoute: MerchantPayoutsRoute,
  MerchantTerminalRoute: MerchantTerminalRoute,
  MerchantTransactionsRoute: MerchantTransactionsRoute,
  MerchantWebhooksRoute: MerchantWebhooksRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AideRoute: AideRouteWithChildren,
  CarrieresRoute: CarrieresRoute,
  CheckoutRoute: CheckoutRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  DeveloppeursRoute: DeveloppeursRoute,
  EligibiliteRoute: EligibiliteRoute,
  EntrepriseRoute: EntrepriseRoute,
  InvestisseursRoute: InvestisseursRoute,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRouteWithChildren,
  MoyensPaiementRoute: MoyensPaiementRoute,
  OuPayerRoute: OuPayerRoute,
  PresseRoute: PresseRoute,
  ProfilRoute: ProfilRoute,
  ScoreRoute: ScoreRoute,
  SignupRoute: SignupRoute,
  SoutienMarchandsRoute: SoutienMarchandsRoute,
  CheckoutMerciRoute: CheckoutMerciRoute,
  PaiementsPlanIdRoute: PaiementsPlanIdRoute,
  PaiementsIndexRoute: PaiementsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
